Repository techbastic/FullStack-HackTech, pull requests merged in 2024-10, with the labels that each got.

#8 feat: define user controller
  backend/src/controllers/userController.js
Labels: enhancement, hacktoberfest

#10 Add Auth and sendotp middleware
  backend/src/Routers/userRouter.js
  backend/src/middlewares/auth.js
  backend/src/middlewares/sendOtp.js
Labels: hacktoberfest, hacktoberfest-accepted

#12 Chatpage UI Completed
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/Chatpage.css
  frontend/src/Chatpage.jsx
  frontend/src/image.png
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
